### ISSUE TITLE
worldmap <- cbind(worldmap,st_coordinates(st_centroid(worldmap))) generate an error

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#1]
Hi P.

First of all, thanks a lot for your great job.

When I run analyses_eurostat.R, I get the following error 
> worldmap <- cbind(worldmap,st_coordinates(st_centroid(worldmap)))
Error in s2_geography_from_wkb(x, oriented = oriented, check = check) : 
  Evaluation error: Found 6 features with invalid spherical geometry.
[14] Loop 96 is not valid: Edge 743 crosses edge 998
[78] Loop 14 edge 0 crosses loop 15 edge 4
[108] Loop 13 is not valid: Edge 1353 has duplicate vertex with edge 1356
[201] Loop 26 edge 0 crosses loop 69 edge 3938
[206] Loop 0 is not valid: Edge 148 is degenerate (duplicate vertex)
[207] Loop 0 is not valid: Edge 141 is degenerate (duplicate vertex).
In addition: Warning message:
In st_centroid.sf(worldmap) :
  st_centroid assumes attributes are constant over geometries of x
> View(worldmap)

Do you know why ?

**Comment by decoderleco** [comment]
Hi !
Did you run first the programm that create data frames you'll need ?

**Comment by JeanGarf** [comment]
Hi P.,

I don't know which program you are speaking of. However, I can see a "worldmap" variable containing 264 lines and 66 columns.

If I add a filter on (name = "France"), it works fine, but if I add a filter on (continent == "Europe").

I get the following error :
Error in s2_geography_from_wkb(x, oriented = oriented, check = check) : 
  Evaluation error: Found 1 feature with invalid spherical geometry.
[47] Loop 26 edge 0 crosses loop 69 edge 3938.

It's like some polygons are not well formed, but I don't know how to find them.
Do you have any idea ?

P.S. : I'm very new to R (I started yesterday !), so I may have missed something

**Comment by decoderleco** [comment]
OK, you have to run creation_tables_deces_europe first. 
My computer crashed this morning.  I'll have to by another... i wont be able to run this since several days.

**Comment by JeanGarf** [comment]
Bad luck for your computer !

I have already run creation_tables_deces_europe first.

I think the problem comes from some data in worldmap, because it works fine if I filter some line...

**Comment by JeanGarf** [comment]
Pierre,

J'ai toujours le problème lors du calcul des Centroids :

Erreur dans s2_geography_from_wkb(x, oriented = oriented, check = check) : 
  Evaluation error: Found 6 features with invalid spherical geometry.
[14] Loop 96 is not valid: Edge 743 crosses edge 998
[78] Loop 14 edge 0 crosses loop 15 edge 4
[108] Loop 13 is not valid: Edge 1353 has duplicate vertex with edge 1356
[201] Loop 26 edge 0 crosses loop 69 edge 3938
[206] Loop 0 is not valid: Edge 148 is degenerate (duplicate vertex)
[207] Loop 0 is not valid: Edge 141 is degenerate (duplicate vertex).
De plus : Message d'avis :
Dans st_centroid.sf(worldmap) :
  st_centroid assumes attributes are constant over geometries of x

As-tu le même problème ?

Aurais-tu une idée ?

**Comment by decoderleco** [comment]
J'ai eu le meme problème.
Avant ça marchait je ne me l'explique pas.
Du coup pour que ça tourne j'ai viré le calcul des centroids car ça sert
juste à calculer la position des noms des pays.

Si on l'enlève il n'y a juste plus les noms. Si tu as une autre méthode
pour l'afficher proprement n'hésite pas.

Les pays avec des territoires partout dans le monde comme la France posent
problème. Il faut mettre le label au centre du territoire principal.

**Comment by JeanGarf** [comment]
Peux-tu pusher ta modif après avoir mergé les #23 et #24 ?

**Comment by decoderleco** [comment]
corrigé
