### ISSUE TITLE
delivrance_medicaments.R

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#10]
ISSUE
The following line aims to convert decimal number with comma to decimal number with dot
open_medic_2020<-open_medic_2020 %>% mutate(BSE=gsub(",",".",BSE))

However, the 1000 separator in the file is also a dot for instance : 32.125,45

the result is a number with two dot : 32.125.45

FIX
First remove dot, then replace comma with dot

**Comment by decoderleco** [comment]
I tried but it did not worked so I abort and I did it with Excel...
If if works for you tell me...

**Comment by decoderleco** [comment]
I merged thx.
