### ISSUE TITLE
Code enhancement

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#12]
ISSUE
This is a generic issue for code enhancement, adding comments, indenting...

**Comment by decoderleco** [comment]
Yes I'm a newbie in R. I juste did all of this to correct the data and offer public analysis.

**Comment by JeanGarf** [comment]
It was not a criticism at all. I very like your work !

I'm also a newbie in R. But in order to contribute some improvement, I needed an Issue number to create a branch.
That's why I created this issue. It is more an improvement than an issue, in fact. 

So I created this issue

**Comment by decoderleco** [comment]
No problem,
I appreciate that you offer some help.
I try to read carefully all that you suggest. It's precious.

I hope that other people will use this code and understand what's going
on...
