### ISSUE TITLE
png are missing in la_mortalite_en_europe.Rmd

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#16]
ISSUE
Lots of png (ÎleDeFrance.png, NouvelleAquitaine.png...) are missing in la_mortalite_en_europe.Rmd

**Comment by decoderleco** [comment]
they are created by deces_francais.R

**Comment by JeanGarf** [comment]
You're right. I was not able to created them because of #15.

Where are created the following images :
domicile.png
flyerspf.png
medictot.png
medicbac.png
fontanet.png
rivotril.png
EHPAD.png
lien_deces_grippe.png
ourworldindata.png

**Comment by decoderleco** [comment]
They were images from internet. I lost everything of it in the crash of my
pc. You can find them on mondialisation.ca. they publied this article.

**Comment by JeanGarf** [comment]
Merged in b47822e484431bdaffcde72b4431a019ebd03e20
