### ISSUE TITLE
medicam.csv is missing when running delivrance_medicaments.R

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#2]
The file medicam.csv is missing.

Where can I get it ?

**Comment by decoderleco** [comment]
Hi ! 
I did not succeded loading them directly from the web, so I did it in Excel a create a .csv
You can find them here : https://assurance-maladie.ameli.fr/etudes-et-donnees/medicaments-type-prescripteur-medicam-2021
Best regards.

**Comment by decoderleco** [comment]
I just added the .csv in the repository

**Comment by JeanGarf** [comment]
Thanks a lot

**Comment by decoderleco** [comment]
you're welcome.
If you know how to add more countries, just tell me.
