### ISSUE TITLE
geodata not defined in analyse_deces_hebdomadaires.R

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#20]
ISSUE
When running analyse_deces_hebdomadaires.R, there is the following error :

> map_data_init <- inner_join(geodata, deces_standard_pays_semaine_plus_40)
Error in inner_join(geodata, deces_standard_pays_semaine_plus_40) : 
  object 'geodata' not found
In addition: Warning message:
`data_frame()` was deprecated in tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 

ANALYSIS
geodata is not defined

**Comment by JeanGarf** [comment]
Pierre,

Pareil, j'ai toujours le problème avec geodata. 

Où est-il récupéré ?

**Comment by decoderleco** [comment]
corrigé

**Comment by JeanGarf** [comment]
Dans quel commit l'as-tu corrigé ?

**Comment by decoderleco** [comment]
Je viens de corriger de nouveau.
J'ai viré le bout de code qui pose problème.
C'était pour faire vidéo avec la carte de l'Europe qui change de couleur en
fonction de la mortalité.
A cette époque je cherchais une vague. J'ai cru pendant longtemps que la
mortalité hivernale était due à des maladies qui se propagent.
J'y ai passé des nuits entières. Pour rien. Il n'y a rien qui se propage.
Les gens meurent plus souvent l'hiver tous en même temps partout donc cette
vidéo ne montre juste rien, autant l'enlever.
