### ISSUE TITLE
Decalage de semaines pour moyenne glissante en multiples de 52

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#28]
ANOMALIE
Lors de la factorisation dans a__f_plot_deces_hebdo_std_moyenne_mobile() (dans #12) , je me suis rendu compte que le décalage de semaine est en général de 51, soit 52 - 1, pour qu'ensuite lors de l'ajout du n° de semaine, ça fasse 52.
Mais pour l'Allemagne, tu as indiqué 209, soit 52 * 4 +1 et non -1. 
De même pour d'autres pays, tu as mis 157 soit 52 * 3 + et non -1.

1) Est-ce une erreur ou moi qui n'ai pas bien compris ?

2) Concernant les lignes verticales, elles sont actuellement comme ceci :

	abline(v=c(53, 105, 158, 210, 262, 314, 366, 419), col="blue", lty=3)

On ne voit pas directement qu'il s'agit de multiples de 52

CORRECTION ATTENDUE
1) S'il y a bien une erreur, il faudrait je pense corriger comme ceci dans a__f_plot_deces_hebdo_std_moyenne_mobile() :

	es_moyenne_mobile$numerosemaine <- 1:nrow(es_moyenne_mobile) + (decalageSemaines - 1)

et faire les appels comme ceci pour faire apparaître les multiples de 52 :

a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_albanie, 1000, 52 * 3)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_allemagne, 30000, 52 * 4)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_armenie, 2000, 52 * 3)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_autriche, 3000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_belgique, 4000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_bulgarie, 5000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_chypre, 300, 52 * 3)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_croatie, 2000, 52 * 2)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_danmark, 2000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_espagne, 25000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_estonie, 500)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_finlande, 2000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_grece, 5000, 52 * 3)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_hongrie, 5000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_islande, 100)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_italie, 30000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_lettonie, 1000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_lichtenstein, 20)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_lituanie, 2000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_luxembourg, 200)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_malte, 200)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_montenegro, 200)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_norvege, 1500)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_paysbas, 6000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_pologne, 17000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_portugal, 6000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_roumanie, 10000, 52 * 3)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_rtcheque, 5000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_serbie, 5000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_slovaquie, 3000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_slovenie, 1000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_suede, 3000)
a__f_plot_deces_hebdo_std_moyenne_mobile(es_deces_standard_pays_semaine_suisse, 3000)

2) Concernant les lignes verticales, on pourrait faire quelque chose ceci :

	annee <- 1:8
	abline(v = annee * 52 - 1, col="blue", lty=3)

On verrait ainsi directement qu'il s'agit de multiples de 52.

Est-ce * 52 - 1 ou * 52 + 1 ?

**Comment by decoderleco** [comment]
Oui c'est normal que tous ne commencent pas pareil car la semaine 1 est
pour la 1ere semaine 2013, mais pour certains pays je n'ai que depuis
2015....

C'est normal que les années ne tombent pas les multiples de 52, car
eurostat utilise un découpage annuel qui compte parfois 53 semaines aux
années. C'est du cas par cas.
