### ISSUE TITLE
R program to generate pyramide_europe_2000 is missing

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#3]
P.,

Which program will generate pyramide_europe_2000.png file ?

**Comment by decoderleco** [comment]
Analyse_eurostat I think. I can't be sure.

**Comment by JeanGarf** [comment]
I don't think so. There's only pyramid_france_2020.png, not europe.

**Comment by decoderleco** [comment]
I read the code on my phone,  it is from line 250 to 276

**Comment by JeanGarf** [comment]
OK, thanks, but the line to generate the file is missing.

I add it

**Comment by decoderleco** [comment]
Ok I merged it thx
