### ISSUE TITLE
Standardiser la vaccination contre la grippe ?

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#30]
Salut Pierre,

Lorsque tu génères le graphique "Medicam_Vaccins_Grippe_Distribues.png", ne faudrait-il pas le standardiser (ou normaliser, je ne sais pas quel est la bonne terminologie) par rapport à la population, voire par tranche d'âge ?

En effet, dans ton article, tu dis qu'il faut tenir compte de la pyramide des âges pour calculer le taux de mortalité.
Il faudrait donc le faire pour tout, non ?

**Comment by decoderleco** [comment]
Pour le passage d'une année sur l'autre ?
Je ne pense pas que ce soit la peine. Il s'agit juste d'une comparaison 2019-2020 et je ne fais pas de calcul précis, je montre uniquement les fortes hausses / baisses.
SI on voulait modéliser quelques chose, oui.

**Comment by JeanGarf** [comment]
OK
