### ISSUE TITLE
Te parait-il normal que la France ne communique plus les décès depuis 2021W24 dans demo_r_mwk_05 ?

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#37]
Bonsoir Pierre,

Je voulais actualiser les données EuroStat pour re-générer les courbes hebdo, mais je vois que la France n'a pas publié ses décès depuis 2021W24 alors que l'Allemagne, la Bulgarie, la pologne l'on déjà fait jusqu'à 2021W27.

Est-ce habituel que la France soit en retard pour fournir ses chiffres ?

Je ne sais pas si Github est le meilleur endroit pour te poser ce type de question, mais je ne sais pas comment te contacter autrement...

**Comment by decoderleco** [comment]
contacte moi sur decoderleco@gmail.com

**Comment by JeanGarf** [comment]
Bon, ça y est, la France a enfin mis ses données jusqu'à la semaine 27.
