### ISSUE TITLE
Analyse des données VAERS

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#38]
Analyser les données VAERS du CDC

**Comment by decoderleco** [comment]
Je ne sais pas si tu as pu lire mon message sur le pull
je disais merci !
Je ne pense pas qu'il existe de data en ligne sur la pharmacovigilance française, mais tu peux trouver les données à la main dans les fiches par vaccin ici :https://ansm.sante.fr/dossiers-thematiques/covid-19-suivi-hebdomadaire-des-cas-deffets-indesirables-des-vaccins
Pour la population des US et le nombre de vaccins distribués je n'en sais rien... J'espérai qu'en postant ce programme un spécialiste USA vienne pour rajouter les données.

**Comment by JeanGarf** [comment]
Salut Pierre,

Non, je n'avais pas vu ton message. 

Merci.

**Comment by JDpw** [comment]
### **_Bugs R_**
Bonjour, 
D'abord bravo pour votre travail impressionnant.
Voici quelques bug relevés sur les fichiers disponibles sur GitHub. Je suis débutant sur Github et je ne sais pas comment les changer, donc je vous les mets dans le message ci-dessous.

Par ailleurs j'ai aussi un soucis avec le fichier 050_delivrance_medicaments.R que j'étudierai plus tard.

Cordialement
 Jérôme Depauw

### Problème : les pyramides des âges europe ne s’affiche pas
**diagnostique** : il y a des « NA » dans plusieurs pays. Du coup lors du regroupement, le résultat de la sommation est « NA » 
**Solution** : faire la sommation en spécifiant « na.rm = TRUE » 
**Code**: (fichier 020_analyses_eurostat.R)

_hommes_femmes2020 <- hommes2020 %>%
		left_join(femmes2020) %>% 
                (...)
						TRUE ~agequinq)) %>%
		group_by(agequinq) %>% 
		summarise(femmes=sum(femmes,**na.rm = TRUE**),   ###### <- **ici** 
				hommes=sum(hommes,**na.rm = TRUE**))  #######  <- **et la**_

et idem pour la pyramide 2000


### Problème : les courbes des décès hebdomadaires s’arrêtent aux années 2020 et 2021
**Diagnostique** : Lors de la construction de la table es_pjan_quinq_pop_week, on ajoute les années 2021 et 2022 comme étant égales à 2020. Or l’année 2021 est déjà présente dans le fichier (avec des valeurs NA). On se retrouve donc avec des doublons pour les semaines de 2021, une fois avec NA, une fois avec la valeur de 2020.
**Solution** : supprimer l’année 2021 avant de commencer
**code** : (fichier 010_creation_tables_deces_europe.R)

_#ajout des années 2021 et 2022 comme étant égales à 2020
############## **attention déjà des donnees en 2021**  ###### <- **ici**
es_pjan_quinq_pop_week <- es_pjan_quinq_pop_week %>% **filter(time != "2021-01-01")** ###### <- **et la**_


### Problème : sur les courbes des décès hebdomadaires ni les échèles horizontales (années) ni les moyennes mobiles n’apparaissent
**Diagnostique** : La colonne numSemaineDepuis2013 de la table es_deces_week_France compte en faite depuis le début de la table, c’est-à-dire 2000.
**Solution** décaler l’indice de 678 pour que la semaine 2013W01 ait le numéro 1
**code** (fichier 010_creation_tables_deces_europe.R)

_# Ajouter une colonne avec numero de semaine depuis 2013
es_deces_week_France$numSemaineDepuis2013 <- (1:nrow(es_deces_week_France))**-678**   ######### <- **ici**_

**Comment by JeanGarf** [comment]
J'ai créé les issues suivantes #45, #46 et #47 pour chacun des problèmes et correctifs proposés par JDpw.

Merci à lui pour ses contributions.
