### ISSUE TITLE
deces_complet_annuel.RDS and deces_standard_pays_semaine.RDS should not be managed by git

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#4]
deces_complet_annuel.RDS and deces_standard_pays_semaine.RDS should not be managed by git, because they are generated by creation_tables_deces_europe.R

**Comment by decoderleco** [comment]
Yes. I'm a beginner in R. I think you'll have to install Rstudio

**Comment by JeanGarf** [comment]
Yes, I did it.

I made some improvements today. I will create some issue to trace them and I will submit them to you as pull requests.

**Comment by decoderleco** [comment]
In fact, I saved it to keep a save of my work.
I can be usefull to compare new results to those.
I prefer keeping them. I think it doesn't block anything.
