### ISSUE TITLE
Créer un graphique des décès quotidiens avec "facet" pour chaque tranche d'âge de 10 ans

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#41]
Salut Pierre,

Ajout de quelques factorisations de code + un graphique synthétique par tranche d'âge pour montrer que l'augmentation des décès quotidiens ne commence à apparaître dans la tranche d'âge des 50-59 ans

**Comment by decoderleco** [comment]
Merci,
Les décès français du mois de juillet sont disponibles, j'essaye de mettre
à jour demain soir le programme, il suffit juste de rajouter l'URL pour les
récupérer.

Un autre personne a posté des issues intéressantes, je ne sais pas si
j'aurai le temps de les traiter avant septembre. Apparemment, les données
annuelles de décès et de populations ont été rajoutées sur eurostat et donc
ça fait des doublons avec les rajouts que j'ai fait depuis les données
hebdomadaires. Tu n'as pas le problème ?
