### ISSUE TITLE
Corriger les TODO concernant l'Allemagne introduits dans #58

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#61]
ANOMALIE
Lors de #58, dans 030_analyse_deces_hebdomadaires, les graphes de l'Allemagne ont été mis en commentaires (avec des TODO), car ils plantaient.

CORRECTION ATTENDUE
Faire en sorte de pouvoir re-générer les graphiques de l'Allemagne

**Comment by decoderleco** [comment]
corrigé.
Le problème venait du fait que l'Allemagne ne fournit pas de données de décès avant 40 ans.
