### ISSUE TITLE
Graphique de l'évolution des décès par Tranche d'âge et par année

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#62]
BESOIN
Disposer d'un Graphique de l'évolution des décès par Tranche d'âge et par année

JUSTIFICATION
Voir si on voit une évolution de la mortalité, en particulier chez les jeunes, suite à la vaccination

**Comment by chewam** [comment]
C'est surement pas assez precis... mais c'est basé sur les chiffres de l'INSEE:
https://deaths.chewam.com/distribution

Le repo: https://github.com/chewam/deaths

**Comment by decoderleco** [comment]
C'est dorénavant fait pour tous les pays européens avec un calcul de différence de mortalité / moyenne pour les plus jeunes.
