### ISSUE TITLE
Erreur lors de l'exécution de 040_deces_francais juste après 030_analyse_deces_hebdomadaires

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#67]
ANOMALIE
Sur a24b3656e31f7e702fa8c4cffd17b9c93a8a9855 (mais j'ai un problème similaire sur a3b9fbbf99d8b7711ec0d5ea53c7d2b8ecff8391), lorsque l'on exécute 030_analyse_deces_hebdomadaires le script se termine par :

Creation image (gen/images/Eurostat/Deces/Hebdo/Std/owid/Deces_vs_Deces_Covid/Est/slovenie.png)
Terminé 030
Il y a eu 20 avis (utilisez warnings() pour les visionner)

Les warnings sont les suivants  : 
> warnings()
Messages d'avis :
1: Removed 440 rows containing non-finite values (stat_smooth).
2: Removed 440 row(s) containing missing values (geom_path).
3: Removed 440 rows containing missing values (geom_text).
4: Removed 440 rows containing missing values (geom_text).
5: Removed 440 rows containing missing values (geom_text).
6: Removed 440 rows containing missing values (geom_text).
7: Problem with `mutate()` column `barre_vax_18_24`.
i `barre_vax_18_24 = case_when(...)`.
i aucun argument pour max ; -Inf est renvoyé
i The warning occurred in group 1: geo = "AM".
8: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé
9: Problem with `mutate()` column `barre_vax_25_49`.
i `barre_vax_25_49 = case_when(...)`.
i aucun argument pour max ; -Inf est renvoyé
i The warning occurred in group 1: geo = "AM".
10: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé
11: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé
12: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé
13: Problem with `mutate()` column `barre_vax_18_24`.
i `barre_vax_18_24 = case_when(...)`.
i aucun argument pour max ; -Inf est renvoyé
i The warning occurred in group 1: geo = "RS".
14: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé
15: Problem with `mutate()` column `barre_vax_25_49`.
i `barre_vax_25_49 = case_when(...)`.
i aucun argument pour max ; -Inf est renvoyé
i The warning occurred in group 1: geo = "RS".
16: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé
17: Problem with `mutate()` column `barre_vax_18_24`.
i `barre_vax_18_24 = case_when(...)`.
i aucun argument pour max ; -Inf est renvoyé
i The warning occurred in group 1: geo = "CH".
18: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé
19: Problem with `mutate()` column `barre_vax_25_49`.
i `barre_vax_25_49 = case_when(...)`.
i aucun argument pour max ; -Inf est renvoyé
i The warning occurred in group 1: geo = "CH".
20: In base::min(temp$numSemaineDepuis2013) :
  aucun argument trouvé pour min ; Inf est renvoyé

A priori, ces warnings correspondent à des pays qui ont toutes les données à NA, dont c'est pas trop grave.

Par contre ensuite, lorsque l'on exécute 040_deces_francais, on obtient l'erreur suivante :

(b__fr_gouv_deces_quotidiens) a été construite
Erreur : Problem with `summarise()` column `nbDeces`.
i `nbDeces = n()`.
x Variable not specified.
i The error occurred in group 1: deces_num_dept = "01", deces_date_complete = 2018-01-01.
Run `rlang::last_error()` to see where the error occurred.

CONTOURNEMENT
Fermer R et relancer directement l'exécution de 005_functions, puis 040_deces_francais, sans exécuter 030_analyse_deces_hebdomadaires et là, ça fonctionne !

(Je suis sous Eclipse 4.16.0/StatET 4.2.4 et R 4.1.2)

CORRECTION ATTENDUE
Après exécution de 030_analyse_deces_hebdomadaires, l'exécution de 040_deces_francais doit se dérouler normalement (i.e. de la même manière que si on n'avait pas exécuté 030_analyse_deces_hebdomadaires juste avant)

**Comment by decoderleco** [comment]
C'est corrigé. Le package rapportools utilisé dans 030 réimplémente les fonctions min, max, n et mutate. Il faut dorénavant les précéder de leurs packages, respectivement base, base, dplyr et dplyr ou alors utiliser la nouvelle fonction avec les bons paramètres.
