### ISSUE TITLE
Anomalie dans a__f_downloadIfNeeded

### ISSUE THREAD

**Issue by JeanGarf** [decoderleco/deces_europe#82]
ANOMALIE
Salut Thierry, j'ai essayé de rajouter le m02 des données de décès 2022, mais j'ai une erreur qui apparaît. ça vient de la fonction a__f_downloadIfNeeded. Il y a un var qui vaut un truc bizarre... Tu aurais le temps de jeter un oeil ?

**Comment by JeanGarf** [comment]
ANALYSE
Il semblerait que le problème ait été introduit dans mon commit b9a450e2f4af95383a3a75cc92da2e8a80b6d7cc.

J'ai introduit une variable locale "downloadedDatas" qui peut entrer en conflit avec celle passée dans var si celle-ci s'appelle justement "downloadedDatas"

**Comment by decoderleco** [comment]
Merci Thierry, ça fonctionne !
